# Moises Abraham Rangel Hernandez
#1951


In [1]:
import numpy as np

In [4]:
arreglo = np.array([0,1,2,3,4,5])

In [5]:
arreglo, type(arreglo)

(array([0, 1, 2, 3, 4, 5]), numpy.ndarray)

In [6]:
notas = [10,9,7,4,8,10]
ar_notas = np.array(notas, dtype=float)

In [8]:
ar_notas, type(ar_notas[0])

(array([10.,  9.,  7.,  4.,  8., 10.]), numpy.float64)

In [9]:
ar_notas_todas = np.array(([0,1,2,3,4,5], notas))
ar_notas_todas

array([[ 0,  1,  2,  3,  4,  5],
       [10,  9,  7,  4,  8, 10]])

In [10]:
print(ar_notas_todas.ndim)
print(ar_notas.ndim)

2
1


In [11]:
print(ar_notas_todas.shape)
print(ar_notas.shape)

(2, 6)
(6,)


In [12]:
arr = np.zeros((2,3), dtype=float)
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [13]:
ar2 = np.ones((3,4), dtype=float)
print(ar2)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [14]:
ar3 = np.identity((4), dtype=float)
print(ar3)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [15]:
ar4 = np.identity((4), dtype=float)
print(ar4)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [16]:
ar5 = np.arange(1,9)
print(ar5)

[1 2 3 4 5 6 7 8]


# Moises Abraham Rangel Hernandez
# 1951
# operaciones basicas

In [18]:
import numpy as np
arr = np.arange(1,9)

In [19]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [20]:
arr.shape =(2,4)
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [21]:
arr + arr

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16]])

In [22]:
arr - arr

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [23]:
arr * arr

array([[ 1,  4,  9, 16],
       [25, 36, 49, 64]])

In [24]:
arr ** arr

array([[       1,        4,       27,      256],
       [    3125,    46656,   823543, 16777216]], dtype=int32)

In [25]:
arr / arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

# Moises Abraham Rangel Hernandez
# 1951
# Algebra lineal

In [26]:
import numpy as np
a = np.array([1,2,3],float)
b = np.array([0,1,1],float)

np.dot(b, a)

5.0

In [29]:
a = np.array([[5,2],[4,8]],float)
b = np.array([[2,4],[5,3]],float)
print(a, "\n----------------")
print(b, "\n----------------")

[[5. 2.]
 [4. 8.]] 
----------------
[[2. 4.]
 [5. 3.]] 
----------------


In [30]:
np.dot(a,b)

array([[20., 26.],
       [48., 40.]])

In [31]:
a @ b

array([[20., 26.],
       [48., 40.]])

In [32]:
a = np.array([[0,1,4],[5,2,3],[1,4,8]],float)
b = np.array([2,3,5],float)
print(a, "\n----------------")
print(b, "\n----------------")

[[0. 1. 4.]
 [5. 2. 3.]
 [1. 4. 8.]] 
----------------
[2. 3. 5.] 
----------------


In [37]:
np.dot(a,b)

array([23., 31., 54.])

In [39]:
a @ b

array([23., 31., 54.])

In [36]:
print(np.matmul(a,b))

[23. 31. 54.]


In [40]:
a = np.array([[8,5],[3,4]])
print(a, "\n----------------")
np.linalg.det(a)

[[8 5]
 [3 4]] 
----------------


17.0

In [42]:
vals, vecs = np.linalg.eig(a)
print(vals, "\n------------------")
print(vecs, "\n------------------")

[10.35889894  1.64110106] 
------------------
[[ 0.90440309 -0.61810602]
 [ 0.4266791   0.78609474]] 
------------------


# Moises Abraham Rangel Hernandez
# 1951
# funciones universales

In [44]:
import numpy as np
a = np.array([2,4,9],float)
a

array([2., 4., 9.])

In [45]:
np.sqrt(a)

array([1.41421356, 2.        , 3.        ])

In [46]:
np.exp(a)

array([7.38905610e+00, 5.45981500e+01, 8.10308393e+03])

In [47]:
np.log(a)

array([0.69314718, 1.38629436, 2.19722458])

In [49]:
np.sin(a)

array([ 0.90929743, -0.7568025 ,  0.41211849])

In [50]:
np.cos(a)

array([-0.41614684, -0.65364362, -0.91113026])

In [51]:
np.mean(a)

5.0

In [52]:
np.std(a)

2.943920288775949

In [53]:
np.var(a)

8.666666666666666

# Moises Abraham Rangel Hernandez
# 1951
# funciones universales binarias

In [54]:
import numpy as np
arr = np.array([5,36,17,18,9])
arr2 = np.array([8,24,17,19,9])

In [55]:
np.add(arr,arr2)

array([13, 60, 34, 37, 18])

In [57]:
np.subtract(arr,arr2)

array([-3, 12,  0, -1,  0])

In [58]:
np.multiply(arr,arr2)

array([ 40, 864, 289, 342,  81])

In [59]:
np.divide(arr,arr2)

array([0.625     , 1.5       , 1.        , 0.94736842, 1.        ])

In [61]:
np.array_equal(arr,arr2)

False

In [62]:
np.fmin(arr,arr2)

array([ 5, 24, 17, 18,  9])

In [63]:
np.fmax(arr,arr2)

array([ 8, 36, 17, 19,  9])

# Moises Abraham Rangel Hernandez
# 1951
# agregar quitar valores

In [65]:
import numpy as np
arr = np.arange(0,20,2)
arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [66]:
arr_float = np.random.rand(4,3)
arr_float

array([[0.00731262, 0.45780769, 0.09741888],
       [0.67687164, 0.68389794, 0.92795268],
       [0.2154549 , 0.17058818, 0.91496992],
       [0.82896098, 0.00358443, 0.57644595]])

In [77]:
arr_ent = np.random.randint(10, size=(2,3))
arr_ent

array([[4, 9, 7],
       [7, 1, 1]])

In [70]:
arr_full = np.full((3,3),6)
arr_full

array([[6, 6, 6],
       [6, 6, 6],
       [6, 6, 6]])

In [73]:
np.append(arr,[12,13,14,51])

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 12, 13, 14, 51])

In [74]:
np.insert(arr,2,[42,34])

array([ 0,  2, 42, 34,  4,  6,  8, 10, 12, 14, 16, 18])

In [78]:
np.delete(arr_ent,1,axis=0)

array([[4, 9, 7]])

# Moises Abraham Rangel Hernandez
# 1951
# Transformaciones

In [79]:
import numpy as np 
arr_ent = np.random.randint(100, size=(3,4))
arr_ent

array([[14, 23, 33, 96],
       [20, 64,  5, 91],
       [46, 14, 99, 55]])

In [81]:
arr_ent.astype(float)

array([[14., 23., 33., 96.],
       [20., 64.,  5., 91.],
       [46., 14., 99., 55.]])

In [82]:
arr_ent

array([[14, 23, 33, 96],
       [20, 64,  5, 91],
       [46, 14, 99, 55]])

In [84]:
arr_ent.sort()
arr_ent

array([[14, 23, 33, 96],
       [ 5, 20, 64, 91],
       [14, 46, 55, 99]])

In [85]:
arr_ent.sort(axis=0)
arr_ent

array([[ 5, 20, 33, 91],
       [14, 23, 55, 96],
       [14, 46, 64, 99]])

In [123]:
arr_ent = arr_ent.reshape(4,3)
arr_ent

array([[ 5, 20, 33],
       [91, 14, 23],
       [55, 96, 14],
       [46, 64, 99]])

In [92]:
plano_arr = arr_ent.flatten()

print(arr_ent)
print(plano_arr)

[[ 5 20 33 91]
 [14 23 55 96]
 [14 46 64 99]]
[ 5 20 33 91 14 23 55 96 14 46 64 99]


In [95]:
lista_arr = plano_arr.tolist()
lista_arr
type(lista_arr)

list

In [99]:
arrays =np.split(arr_ent,3)
arrays

[array([[ 5, 20, 33, 91]]),
 array([[14, 23, 55, 96]]),
 array([[14, 46, 64, 99]])]

In [100]:
np.concatenate((arrays[1],arrays[0]),axis=0)

array([[14, 23, 55, 96],
       [ 5, 20, 33, 91]])

In [102]:
t_arr = arr_ent.T
t_arr

array([[ 5, 14, 14],
       [20, 23, 46],
       [33, 55, 64],
       [91, 96, 99]])

# Moises Abraham Rangel Hernandez
# 1951
# indexacion

In [105]:
import numpy as np
a= np.array(range(64)).reshape(8,8)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60, 61, 62, 63]])

In [106]:
a[1,1]

9

In [111]:
a[0:7:2,]

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [48, 49, 50, 51, 52, 53, 54, 55]])

In [112]:
a[1,3:]

array([11, 12, 13, 14, 15])

In [113]:
a[[1,3,5],[3,6,7]]

array([11, 30, 47])

In [114]:
a[[1,3,5],::3]

array([[ 8, 11, 14],
       [24, 27, 30],
       [40, 43, 46]])

In [115]:
data = np.arange(8)
data

array([0, 1, 2, 3, 4, 5, 6, 7])

In [116]:
data <4

array([ True,  True,  True,  True, False, False, False, False])

In [117]:
data[data<4]

array([0, 1, 2, 3])

In [118]:
amigo =np.array(["cristian","daniel","yami","tania","paola","montana","moises"])

In [120]:
"moises" in amigo

True

In [122]:
amigo[amigo!="moises"]

array(['cristian', 'daniel', 'yami', 'tania', 'paola', 'montana'],
      dtype='<U8')